//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17929
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MainPower.DrawingsDatabase.Gui.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "10.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"Amberley;Balmoral;Bennetts;Oxford;Cheviot;Claverley;Cust;Greta;Hanmer;Hawarden;Leader;Leslie Hills;Lochiel;Ludstone;Marble Point;Mckenzies Road;Motunau;Mouse Point;Oaro;Omihi;Percival St;Rangiora North;Kaiapoi S1;Southbrook;Kaiapoi North;Pegasus;Swannanoa;Rangiora West;")]
        public string Substations {
            get {
                return ((string)(this["Substations"]));
            }
            set {
                this["Substations"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string SearchColumns {
            get {
                return ((string)(this["SearchColumns"]));
            }
            set {
                this["SearchColumns"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string RecentTemplates {
            get {
                return ((string)(this["RecentTemplates"]));
            }
            set {
                this["RecentTemplates"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string SavedSearch {
            get {
                return ((string)(this["SavedSearch"]));
            }
            set {
                this["SavedSearch"] = value;
            }
        }
    }
}
