#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MainPower.DrawingsDatabase.DatabaseHelper
{
    using System.Data.Linq;
    using System.Data.Linq.Mapping;
    using System.Data;
    using System.Collections.Generic;
    using System.Reflection;
    using System.Linq;
    using System.Linq.Expressions;
    using System.ComponentModel;
    using System;
    using System.Runtime.Serialization;


    [global::System.Data.Linq.Mapping.DatabaseAttribute(Name = "Drawings")]
    public partial class DrawingsDataContext : System.Data.Linq.DataContext
    {

        private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();

        #region Extensibility Method Definitions
        partial void OnCreated();
        partial void InsertDrawing(Drawing instance);
        partial void UpdateDrawing(Drawing instance);
        partial void DeleteDrawing(Drawing instance);
        #endregion

        public DrawingsDataContext() :
            base(Properties.Settings.Default.DrawingsConnectionString, mappingSource)
        {
            OnCreated();
        }

        public DrawingsDataContext(System.Data.IDbConnection connection) :
            base(connection, mappingSource)
        {
            OnCreated();
        }

        public DrawingsDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) :
            base(connection, mappingSource)
        {
            OnCreated();
        }

        public DrawingsDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) :
            base(connection, mappingSource)
        {
            OnCreated();
        }

        public System.Data.Linq.Table<Drawing> Drawings
        {
            get
            {
                return this.GetTable<Drawing>();
            }
        }
    }

    [global::System.Data.Linq.Mapping.TableAttribute(Name = "dbo.Drawings")]
    [Serializable]
    public partial class Drawing : INotifyPropertyChanging, INotifyPropertyChanged, ICloneable
    {

        private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);

        private int _ID = default(int);

        private DrawingCategory _CATEGORY;

        private DrawingStatus _STATUS;

        private string _CONSULTANT;

        private string _FILENAME;

        private string _SCALE;

        private string _LEGACY_DRAWING;

        private string _NUMBER;

        private string _PROJECT_TITLE;

        private string _TITLE_LINE_1;

        private System.Nullable<bool> _ELECTRONIC;

        private string _TITLE_LINE_2;

        private string _TITLE_LINE_3;

        private string _TITLE_LINE_4;

        private string _SHEET;

        private string _SHEET_SIZE;

        private string _SHEET_REVISION;

        private string _DRAWN_BY;

        private System.Nullable<System.DateTime> _DRAWN_DATE;

        private string _CHECKED_BY;

        private System.Nullable<System.DateTime> _CHECKED_DATE;

        private string _APPRV_BY;

        private System.Nullable<System.DateTime> _APPRV_DATE;

        private string _REV_A;

        private string _REV_B;

        private string _REV_C;

        private string _REV_D;

        private string _REV_E;

        private string _REV_F;

        private string _REV_G;

        private string _DRAWN_BY_A;

        private string _DRAWN_BY_B;

        private string _DRAWN_BY_C;

        private string _DRAWN_BY_D;

        private string _DRAWN_BY_E;

        private string _DRAWN_BY_F;

        private string _DRAWN_BY_G;

        private System.Nullable<System.DateTime> _DATE_A;

        private System.Nullable<System.DateTime> _DATE_B;

        private System.Nullable<System.DateTime> _DATE_C;

        private System.Nullable<System.DateTime> _DATE_D;

        private System.Nullable<System.DateTime> _DATE_E;

        private System.Nullable<System.DateTime> _DATE_F;

        private System.Nullable<System.DateTime> _DATE_G;

        private string _DESCRIPTION_A;

        private string _DESCRIPTION_B;

        private string _DESCRIPTION_C;

        private string _DESCRIPTION_D;

        private string _DESCRIPTION_E;

        private string _DESCRIPTION_F;

        private string _DESCRIPTION_G;

        private string _APPRV_BY_A;

        private string _APPRV_BY_B;

        private string _APPRV_BY_C;

        private string _APPRV_BY_D;

        private string _APPRV_BY_E;

        private string _APPRV_BY_F;

        private string _APPRV_BY_G;

        private string _Comments;

        #region Extensibility Method Definitions
        partial void OnLoaded();
        partial void OnValidate(System.Data.Linq.ChangeAction action);
        partial void OnCreated();
        partial void OnCategoryChanging(DrawingCategory value);
        partial void OnCategoryChanged();
        partial void OnStatusChanging(DrawingStatus value);
        partial void OnStatusChanged();
        partial void OnConsultantChanging(string value);
        partial void OnConsultantChanged();
        partial void OnFilenameChanging(string value);
        partial void OnFilenameChanged();
        partial void OnScaleChanging(string value);
        partial void OnScaleChanged();
        partial void OnLegacyDrawingChanging(string value);
        partial void OnLegacyDrawingChanged();
        partial void OnNumberChanging(string value);
        partial void OnNumberChanged();
        partial void OnProjectTitleChanging(string value);
        partial void OnProjectTitleChanged();
        partial void OnTitleLine1Changing(string value);
        partial void OnTitleLine1Changed();
        partial void OnElectronicChanging(System.Nullable<bool> value);
        partial void OnElectronicChanged();
        partial void OnTitleLine2Changing(string value);
        partial void OnTitleLine2Changed();
        partial void OnTitleLine3Changing(string value);
        partial void OnTitleLine3Changed();
        partial void OnTitleLine4Changing(string value);
        partial void OnTitleLine4Changed();
        partial void OnSheetChanging(string value);
        partial void OnSheetChanged();
        partial void OnSheetSizeChanging(string value);
        partial void OnSheetSizeChanged();
        partial void OnSheetRevisionChanging(string value);
        partial void OnSheetRevisionChanged();
        partial void OnDrawnByChanging(string value);
        partial void OnDrawnByChanged();
        partial void OnDrawnDateChanging(System.Nullable<System.DateTime> value);
        partial void OnDrawnDateChanged();
        partial void OnCheckedByChanging(string value);
        partial void OnCheckedByChanged();
        partial void OnCheckedDateChanging(System.Nullable<System.DateTime> value);
        partial void OnCheckedDateChanged();
        partial void OnApprovedByChanging(string value);
        partial void OnApprovedByChanged();
        partial void OnApprovedDateChanging(System.Nullable<System.DateTime> value);
        partial void OnApprovedDateChanged();
        partial void OnRevAChanging(string value);
        partial void OnRevAChanged();
        partial void OnRevBChanging(string value);
        partial void OnRevBChanged();
        partial void OnRevCChanging(string value);
        partial void OnRevCChanged();
        partial void OnRevDChanging(string value);
        partial void OnRevDChanged();
        partial void OnRevEChanging(string value);
        partial void OnRevEChanged();
        partial void OnRevFChanging(string value);
        partial void OnRevFChanged();
        partial void OnRevGChanging(string value);
        partial void OnRevGChanged();
        partial void OnDrawnByRevAChanging(string value);
        partial void OnDrawnByRevAChanged();
        partial void OnDrawnByRevBChanging(string value);
        partial void OnDrawnByRevBChanged();
        partial void OnDrawnByRevCChanging(string value);
        partial void OnDrawnByRevCChanged();
        partial void OnDrawnByRevDChanging(string value);
        partial void OnDrawnByRevDChanged();
        partial void OnDrawnByRevEChanging(string value);
        partial void OnDrawnByRevEChanged();
        partial void OnDrawnByRevFChanging(string value);
        partial void OnDrawnByRevFChanged();
        partial void OnDrawnByRevGChanging(string value);
        partial void OnDrawnByRevGChanged();
        partial void OnDateRevAChanging(System.Nullable<System.DateTime> value);
        partial void OnDateRevAChanged();
        partial void OnDateRevBChanging(System.Nullable<System.DateTime> value);
        partial void OnDateRevBChanged();
        partial void OnDateRevCChanging(System.Nullable<System.DateTime> value);
        partial void OnDateRevCChanged();
        partial void OnDateRevDChanging(System.Nullable<System.DateTime> value);
        partial void OnDateRevDChanged();
        partial void OnDateRevEChanging(System.Nullable<System.DateTime> value);
        partial void OnDateRevEChanged();
        partial void OnDateRevFChanging(System.Nullable<System.DateTime> value);
        partial void OnDateRevFChanged();
        partial void OnDateRevGChanging(System.Nullable<System.DateTime> value);
        partial void OnDateRevGChanged();
        partial void OnDescriptionRevAChanging(string value);
        partial void OnDescriptionRevAChanged();
        partial void OnDescriptionRevBChanging(string value);
        partial void OnDescriptionRevBChanged();
        partial void OnDescriptionRevCChanging(string value);
        partial void OnDescriptionRevCChanged();
        partial void OnDescriptionRevDChanging(string value);
        partial void OnDescriptionRevDChanged();
        partial void OnDescriptionRevEChanging(string value);
        partial void OnDescriptionRevEChanged();
        partial void OnDescriptionRevFChanging(string value);
        partial void OnDescriptionRevFChanged();
        partial void OnDescriptionRevGChanging(string value);
        partial void OnDescriptionRevGChanged();
        partial void OnApprovedByRevAChanging(string value);
        partial void OnApprovedByRevAChanged();
        partial void OnApprovedByRevBChanging(string value);
        partial void OnApprovedByRevBChanged();
        partial void OnApprovedByRevCChanging(string value);
        partial void OnApprovedByRevCChanged();
        partial void OnApprovedByRevDChanging(string value);
        partial void OnApprovedByRevDChanged();
        partial void OnApprovedByRevEChanging(string value);
        partial void OnApprovedByRevEChanged();
        partial void OnApprovedByRevFChanging(string value);
        partial void OnApprovedByRevFChanged();
        partial void OnApprovedByRevGChanging(string value);
        partial void OnApprovedByRevGChanged();
        partial void OnCommentsChanging(string value);
        partial void OnCommentsChanged();
        #endregion

        public Drawing()
        {
            OnCreated();
        }

        [global::System.Data.Linq.Mapping.ColumnAttribute(Storage = "_ID", AutoSync = AutoSync.OnInsert, DbType = "Int NOT NULL IDENTITY", IsPrimaryKey = true, IsDbGenerated = true, UpdateCheck = UpdateCheck.Never)]
        public int Id
        {
            get
            {
                return this._ID;
            }
        }

        [global::System.Data.Linq.Mapping.ColumnAttribute(Name = "CATEGORY", Storage = "_CATEGORY", DbType = "Int NOT NULL", CanBeNull = false)]
        public DrawingCategory Category
        {
            get
            {
                return this._CATEGORY;
            }
            set
            {
                if ((this._CATEGORY != value))
                {
                    this.OnCategoryChanging(value);
                    this.SendPropertyChanging();
                    this._CATEGORY = value;
                    this.SendPropertyChanged("Category");
                    this.OnCategoryChanged();
                }
            }
        }

        [global::System.Data.Linq.Mapping.ColumnAttribute(Name = "STATUS", Storage = "_STATUS", DbType = "Int NOT NULL", CanBeNull = false)]
        public DrawingStatus Status
        {
            get
            {
                return this._STATUS;
            }
            set
            {
                if ((this._STATUS != value))
                {
                    this.OnStatusChanging(value);
                    this.SendPropertyChanging();
                    this._STATUS = value;
                    this.SendPropertyChanged("Status");
                    this.OnStatusChanged();
                }
            }
        }

        [global::System.Data.Linq.Mapping.ColumnAttribute(Name = "CONSULTANT", Storage = "_CONSULTANT", DbType = "NVarChar(256)")]
        public string Consultant
        {
            get
            {
                return this._CONSULTANT;
            }
            set
            {
                if ((this._CONSULTANT != value))
                {
                    this.OnConsultantChanging(value);
                    this.SendPropertyChanging();
                    this._CONSULTANT = value;
                    this.SendPropertyChanged("Consultant");
                    this.OnConsultantChanged();
                }
            }
        }

        [Editor(typeof(FileChooserEditor), typeof(FileChooserEditor))]
        [global::System.Data.Linq.Mapping.ColumnAttribute(Name = "FILENAME", Storage = "_FILENAME", DbType = "NVarChar(512)")]
        public string FileName
        {
            get
            {
                return this._FILENAME;
            }
            set
            {
                if ((this._FILENAME != value))
                {
                    this.OnFilenameChanging(value);
                    this.SendPropertyChanging();
                    this._FILENAME = value;
                    this.SendPropertyChanged("Filename");
                    this.OnFilenameChanged();
                }
            }
        }

        [global::System.Data.Linq.Mapping.ColumnAttribute(Name = "SCALE", Storage = "_SCALE", DbType = "NVarChar(10)")]
        public string Scale
        {
            get
            {
                return this._SCALE;
            }
            set
            {
                if ((this._SCALE != value))
                {
                    this.OnScaleChanging(value);
                    this.SendPropertyChanging();
                    this._SCALE = value;
                    this.SendPropertyChanged("Scale");
                    this.OnScaleChanged();
                }
            }
        }

        [global::System.Data.Linq.Mapping.ColumnAttribute(Name = "LEGACY_DRAWING", Storage = "_LEGACY_DRAWING", DbType = "NVarChar(256)")]
        public string LegacyDrawing
        {
            get
            {
                return this._LEGACY_DRAWING;
            }
            set
            {
                if ((this._LEGACY_DRAWING != value))
                {
                    this.OnLegacyDrawingChanging(value);
                    this.SendPropertyChanging();
                    this._LEGACY_DRAWING = value;
                    this.SendPropertyChanged("LegacyDrawing");
                    this.OnLegacyDrawingChanged();
                }
            }
        }

        [global::System.Data.Linq.Mapping.ColumnAttribute(Name = "NUMBER", Storage = "_NUMBER", DbType = "NVarChar(40) NOT NULL", CanBeNull = false)]
        public string Number
        {
            get
            {
                return this._NUMBER;
            }
            set
            {
                if ((this._NUMBER != value))
                {
                    this.OnNumberChanging(value);
                    this.SendPropertyChanging();
                    this._NUMBER = value;
                    this.SendPropertyChanged("Number");
                    this.OnNumberChanged();
                }
            }
        }

        [global::System.Data.Linq.Mapping.ColumnAttribute(Name = "PROJECT_TITLE", Storage = "_PROJECT_TITLE", DbType = "NVarChar(256)")]
        public string ProjectTitle
        {
            get
            {
                return this._PROJECT_TITLE;
            }
            set
            {
                if ((this._PROJECT_TITLE != value))
                {
                    this.OnProjectTitleChanging(value);
                    this.SendPropertyChanging();
                    this._PROJECT_TITLE = value;
                    this.SendPropertyChanged("ProjectTitle");
                    this.OnProjectTitleChanged();
                }
            }
        }

        [global::System.Data.Linq.Mapping.ColumnAttribute(Name = "TITLE_LINE_1", Storage = "_TITLE_LINE_1", DbType = "NVarChar(256)")]
        public string TitleLine1
        {
            get
            {
                return this._TITLE_LINE_1;
            }
            set
            {
                if ((this._TITLE_LINE_1 != value))
                {
                    this.OnTitleLine1Changing(value);
                    this.SendPropertyChanging();
                    this._TITLE_LINE_1 = value;
                    this.SendPropertyChanged("TitleLine1");
                    this.OnTitleLine1Changed();
                }
            }
        }

        [global::System.Data.Linq.Mapping.ColumnAttribute(Name = "ELECTRONIC", Storage = "_ELECTRONIC", DbType = "Bit")]
        public System.Nullable<bool> Electronic
        {
            get
            {
                return this._ELECTRONIC;
            }
            set
            {
                if ((this._ELECTRONIC != value))
                {
                    this.OnElectronicChanging(value);
                    this.SendPropertyChanging();
                    this._ELECTRONIC = value;
                    this.SendPropertyChanged("Electronic");
                    this.OnElectronicChanged();
                }
            }
        }

        [global::System.Data.Linq.Mapping.ColumnAttribute(Name = "TITLE_LINE_2", Storage = "_TITLE_LINE_2", DbType = "NVarChar(256)")]
        public string TitleLine2
        {
            get
            {
                return this._TITLE_LINE_2;
            }
            set
            {
                if ((this._TITLE_LINE_2 != value))
                {
                    this.OnTitleLine2Changing(value);
                    this.SendPropertyChanging();
                    this._TITLE_LINE_2 = value;
                    this.SendPropertyChanged("TitleLine2");
                    this.OnTitleLine2Changed();
                }
            }
        }

        [global::System.Data.Linq.Mapping.ColumnAttribute(Name = "TITLE_LINE_3", Storage = "_TITLE_LINE_3", DbType = "NVarChar(256)")]
        public string TitleLine3
        {
            get
            {
                return this._TITLE_LINE_3;
            }
            set
            {
                if ((this._TITLE_LINE_3 != value))
                {
                    this.OnTitleLine3Changing(value);
                    this.SendPropertyChanging();
                    this._TITLE_LINE_3 = value;
                    this.SendPropertyChanged("TitleLine3");
                    this.OnTitleLine3Changed();
                }
            }
        }

        [global::System.Data.Linq.Mapping.ColumnAttribute(Name = "TITLE_LINE_4", Storage = "_TITLE_LINE_4", DbType = "NChar(10)")]
        public string TitleLine4
        {
            get
            {
                return this._TITLE_LINE_4;
            }
            set
            {
                if ((this._TITLE_LINE_4 != value))
                {
                    this.OnTitleLine4Changing(value);
                    this.SendPropertyChanging();
                    this._TITLE_LINE_4 = value;
                    this.SendPropertyChanged("TitleLine4");
                    this.OnTitleLine4Changed();
                }
            }
        }

        [global::System.Data.Linq.Mapping.ColumnAttribute(Name = "SHEET", Storage = "_SHEET", DbType = "NVarChar(40) NOT NULL", CanBeNull = false)]
        public string Sheet
        {
            get
            {
                return this._SHEET;
            }
            set
            {
                if ((this._SHEET != value))
                {
                    this.OnSheetChanging(value);
                    this.SendPropertyChanging();
                    this._SHEET = value;
                    this.SendPropertyChanged("Sheet");
                    this.OnSheetChanged();
                }
            }
        }

        [global::System.Data.Linq.Mapping.ColumnAttribute(Name = "SHEET_SIZE", Storage = "_SHEET_SIZE", DbType = "NVarChar(10)")]
        public string SheetSize
        {
            get
            {
                return this._SHEET_SIZE;
            }
            set
            {
                if ((this._SHEET_SIZE != value))
                {
                    this.OnSheetSizeChanging(value);
                    this.SendPropertyChanging();
                    this._SHEET_SIZE = value;
                    this.SendPropertyChanged("SheetSize");
                    this.OnSheetSizeChanged();
                }
            }
        }

        [global::System.Data.Linq.Mapping.ColumnAttribute(Name = "SHEET_REVISION", Storage = "_SHEET_REVISION", DbType = "NVarChar(10)")]
        public string SheetRevision
        {
            get
            {
                return this._SHEET_REVISION;
            }
            set
            {
                if ((this._SHEET_REVISION != value))
                {
                    this.OnSheetRevisionChanging(value);
                    this.SendPropertyChanging();
                    this._SHEET_REVISION = value;
                    this.SendPropertyChanged("SheetRevision");
                    this.OnSheetRevisionChanged();
                }
            }
        }

        [global::System.Data.Linq.Mapping.ColumnAttribute(Name = "DRAWN_BY", Storage = "_DRAWN_BY", DbType = "NVarChar(20)")]
        public string DrawnBy
        {
            get
            {
                return this._DRAWN_BY;
            }
            set
            {
                if ((this._DRAWN_BY != value))
                {
                    this.OnDrawnByChanging(value);
                    this.SendPropertyChanging();
                    this._DRAWN_BY = value;
                    this.SendPropertyChanged("DrawnBy");
                    this.OnDrawnByChanged();
                }
            }
        }

        [global::System.Data.Linq.Mapping.ColumnAttribute(Name = "DRAWN_DATE", Storage = "_DRAWN_DATE", DbType = "DateTime")]
        public System.Nullable<System.DateTime> DrawnDate
        {
            get
            {
                return this._DRAWN_DATE;
            }
            set
            {
                if ((this._DRAWN_DATE != value))
                {
                    this.OnDrawnDateChanging(value);
                    this.SendPropertyChanging();
                    this._DRAWN_DATE = value;
                    this.SendPropertyChanged("DrawnDate");
                    this.OnDrawnDateChanged();
                }
            }
        }

        [global::System.Data.Linq.Mapping.ColumnAttribute(Name = "CHECKED_BY", Storage = "_CHECKED_BY", DbType = "NVarChar(20)")]
        public string CheckedBy
        {
            get
            {
                return this._CHECKED_BY;
            }
            set
            {
                if ((this._CHECKED_BY != value))
                {
                    this.OnCheckedByChanging(value);
                    this.SendPropertyChanging();
                    this._CHECKED_BY = value;
                    this.SendPropertyChanged("CheckedBy");
                    this.OnCheckedByChanged();
                }
            }
        }

        [global::System.Data.Linq.Mapping.ColumnAttribute(Name = "CHECKED_DATE", Storage = "_CHECKED_DATE", DbType = "DateTime")]
        public System.Nullable<System.DateTime> CheckedDate
        {
            get
            {
                return this._CHECKED_DATE;
            }
            set
            {
                if ((this._CHECKED_DATE != value))
                {
                    this.OnCheckedDateChanging(value);
                    this.SendPropertyChanging();
                    this._CHECKED_DATE = value;
                    this.SendPropertyChanged("CheckedDate");
                    this.OnCheckedDateChanged();
                }
            }
        }

        [global::System.Data.Linq.Mapping.ColumnAttribute(Name = "APPRV_BY", Storage = "_APPRV_BY", DbType = "NVarChar(20)")]
        public string ApprovedBy
        {
            get
            {
                return this._APPRV_BY;
            }
            set
            {
                if ((this._APPRV_BY != value))
                {
                    this.OnApprovedByChanging(value);
                    this.SendPropertyChanging();
                    this._APPRV_BY = value;
                    this.SendPropertyChanged("ApprovedBy");
                    this.OnApprovedByChanged();
                }
            }
        }

        [global::System.Data.Linq.Mapping.ColumnAttribute(Name = "APPRV_DATE", Storage = "_APPRV_DATE", DbType = "DateTime")]
        public System.Nullable<System.DateTime> ApprovedDate
        {
            get
            {
                return this._APPRV_DATE;
            }
            set
            {
                if ((this._APPRV_DATE != value))
                {
                    this.OnApprovedDateChanging(value);
                    this.SendPropertyChanging();
                    this._APPRV_DATE = value;
                    this.SendPropertyChanged("ApprovedDate");
                    this.OnApprovedDateChanged();
                }
            }
        }

        [Category("Rev A")]
        [global::System.Data.Linq.Mapping.ColumnAttribute(Name = "REV_A", Storage = "_REV_A", DbType = "NVarChar(10)")]
        public string RevA
        {
            get
            {
                return this._REV_A;
            }
            set
            {
                if ((this._REV_A != value))
                {
                    this.OnRevAChanging(value);
                    this.SendPropertyChanging();
                    this._REV_A = value;
                    this.SendPropertyChanged("RevA");
                    this.OnRevAChanged();
                }
            }
        }

        [Category("Rev B")]
        [global::System.Data.Linq.Mapping.ColumnAttribute(Name = "REV_B", Storage = "_REV_B", DbType = "NVarChar(10)")]
        public string RevB
        {
            get
            {
                return this._REV_B;
            }
            set
            {
                if ((this._REV_B != value))
                {
                    this.OnRevBChanging(value);
                    this.SendPropertyChanging();
                    this._REV_B = value;
                    this.SendPropertyChanged("RevB");
                    this.OnRevBChanged();
                }
            }
        }

        [Category("Rev C")]
        [global::System.Data.Linq.Mapping.ColumnAttribute(Name = "REV_C", Storage = "_REV_C", DbType = "NVarChar(10)")]
        public string RevC
        {
            get
            {
                return this._REV_C;
            }
            set
            {
                if ((this._REV_C != value))
                {
                    this.OnRevCChanging(value);
                    this.SendPropertyChanging();
                    this._REV_C = value;
                    this.SendPropertyChanged("RevC");
                    this.OnRevCChanged();
                }
            }
        }

        [Category("Rev D")]
        [global::System.Data.Linq.Mapping.ColumnAttribute(Name = "REV_D", Storage = "_REV_D", DbType = "NVarChar(10)")]
        public string RevD
        {
            get
            {
                return this._REV_D;
            }
            set
            {
                if ((this._REV_D != value))
                {
                    this.OnRevDChanging(value);
                    this.SendPropertyChanging();
                    this._REV_D = value;
                    this.SendPropertyChanged("RevD");
                    this.OnRevDChanged();
                }
            }
        }

        [Category("Rev E")]
        [global::System.Data.Linq.Mapping.ColumnAttribute(Name = "REV_E", Storage = "_REV_E", DbType = "NVarChar(10)")]
        public string RevE
        {
            get
            {
                return this._REV_E;
            }
            set
            {
                if ((this._REV_E != value))
                {
                    this.OnRevEChanging(value);
                    this.SendPropertyChanging();
                    this._REV_E = value;
                    this.SendPropertyChanged("RevE");
                    this.OnRevEChanged();
                }
            }
        }

        [Category("Rev F")]
        [global::System.Data.Linq.Mapping.ColumnAttribute(Name = "REV_F", Storage = "_REV_F", DbType = "NVarChar(10)")]
        public string RevF
        {
            get
            {
                return this._REV_F;
            }
            set
            {
                if ((this._REV_F != value))
                {
                    this.OnRevFChanging(value);
                    this.SendPropertyChanging();
                    this._REV_F = value;
                    this.SendPropertyChanged("RevF");
                    this.OnRevFChanged();
                }
            }
        }

        [Category("Rev G")]
        [global::System.Data.Linq.Mapping.ColumnAttribute(Name = "REV_G", Storage = "_REV_G", DbType = "NVarChar(10)")]
        public string RevG
        {
            get
            {
                return this._REV_G;
            }
            set
            {
                if ((this._REV_G != value))
                {
                    this.OnRevGChanging(value);
                    this.SendPropertyChanging();
                    this._REV_G = value;
                    this.SendPropertyChanged("RevG");
                    this.OnRevGChanged();
                }
            }
        }

        [Category("Rev A")]
        [global::System.Data.Linq.Mapping.ColumnAttribute(Name = "DRAWN_BY_A", Storage = "_DRAWN_BY_A", DbType = "NVarChar(20)")]
        public string DrawnByRevA
        {
            get
            {
                return this._DRAWN_BY_A;
            }
            set
            {
                if ((this._DRAWN_BY_A != value))
                {
                    this.OnDrawnByRevAChanging(value);
                    this.SendPropertyChanging();
                    this._DRAWN_BY_A = value;
                    this.SendPropertyChanged("DrawnByRevA");
                    this.OnDrawnByRevAChanged();
                }
            }
        }

        [Category("Rev B")]
        [global::System.Data.Linq.Mapping.ColumnAttribute(Name = "DRAWN_BY_B", Storage = "_DRAWN_BY_B", DbType = "NVarChar(20)")]
        public string DrawnByRevB
        {
            get
            {
                return this._DRAWN_BY_B;
            }
            set
            {
                if ((this._DRAWN_BY_B != value))
                {
                    this.OnDrawnByRevBChanging(value);
                    this.SendPropertyChanging();
                    this._DRAWN_BY_B = value;
                    this.SendPropertyChanged("DrawnByRevB");
                    this.OnDrawnByRevBChanged();
                }
            }
        }

        [Category("Rev C")]
        [global::System.Data.Linq.Mapping.ColumnAttribute(Name = "DRAWN_BY_C", Storage = "_DRAWN_BY_C", DbType = "NVarChar(20)")]
        public string DrawnByRevC
        {
            get
            {
                return this._DRAWN_BY_C;
            }
            set
            {
                if ((this._DRAWN_BY_C != value))
                {
                    this.OnDrawnByRevCChanging(value);
                    this.SendPropertyChanging();
                    this._DRAWN_BY_C = value;
                    this.SendPropertyChanged("DrawnByRevC");
                    this.OnDrawnByRevCChanged();
                }
            }
        }

        [Category("Rev D")]
        [global::System.Data.Linq.Mapping.ColumnAttribute(Name = "DRAWN_BY_D", Storage = "_DRAWN_BY_D", DbType = "NVarChar(20)")]
        public string DrawnByRevD
        {
            get
            {
                return this._DRAWN_BY_D;
            }
            set
            {
                if ((this._DRAWN_BY_D != value))
                {
                    this.OnDrawnByRevDChanging(value);
                    this.SendPropertyChanging();
                    this._DRAWN_BY_D = value;
                    this.SendPropertyChanged("DrawnByRevD");
                    this.OnDrawnByRevDChanged();
                }
            }
        }

        [Category("Rev E")]
        [global::System.Data.Linq.Mapping.ColumnAttribute(Name = "DRAWN_BY_E", Storage = "_DRAWN_BY_E", DbType = "NVarChar(20)")]
        public string DrawnByRevE
        {
            get
            {
                return this._DRAWN_BY_E;
            }
            set
            {
                if ((this._DRAWN_BY_E != value))
                {
                    this.OnDrawnByRevEChanging(value);
                    this.SendPropertyChanging();
                    this._DRAWN_BY_E = value;
                    this.SendPropertyChanged("DrawnByRevE");
                    this.OnDrawnByRevEChanged();
                }
            }
        }

        [Category("Rev F")]
        [global::System.Data.Linq.Mapping.ColumnAttribute(Name = "DRAWN_BY_F", Storage = "_DRAWN_BY_F", DbType = "NVarChar(20)")]
        public string DrawnByRevF
        {
            get
            {
                return this._DRAWN_BY_F;
            }
            set
            {
                if ((this._DRAWN_BY_F != value))
                {
                    this.OnDrawnByRevFChanging(value);
                    this.SendPropertyChanging();
                    this._DRAWN_BY_F = value;
                    this.SendPropertyChanged("DrawnByRevF");
                    this.OnDrawnByRevFChanged();
                }
            }
        }

        [Category("Rev G")]
        [global::System.Data.Linq.Mapping.ColumnAttribute(Name = "DRAWN_BY_G", Storage = "_DRAWN_BY_G", DbType = "NVarChar(20)")]
        public string DrawnByRevG
        {
            get
            {
                return this._DRAWN_BY_G;
            }
            set
            {
                if ((this._DRAWN_BY_G != value))
                {
                    this.OnDrawnByRevGChanging(value);
                    this.SendPropertyChanging();
                    this._DRAWN_BY_G = value;
                    this.SendPropertyChanged("DrawnByRevG");
                    this.OnDrawnByRevGChanged();
                }
            }
        }

        [Category("Rev A")]
        [global::System.Data.Linq.Mapping.ColumnAttribute(Name = "DATE_A", Storage = "_DATE_A", DbType = "DateTime")]
        public System.Nullable<System.DateTime> DateRevA
        {
            get
            {
                return this._DATE_A;
            }
            set
            {
                if ((this._DATE_A != value))
                {
                    this.OnDateRevAChanging(value);
                    this.SendPropertyChanging();
                    this._DATE_A = value;
                    this.SendPropertyChanged("DateRevA");
                    this.OnDateRevAChanged();
                }
            }
        }

        [Category("Rev B")]
        [global::System.Data.Linq.Mapping.ColumnAttribute(Name = "DATE_B", Storage = "_DATE_B", DbType = "DateTime")]
        public System.Nullable<System.DateTime> DateRevB
        {
            get
            {
                return this._DATE_B;
            }
            set
            {
                if ((this._DATE_B != value))
                {
                    this.OnDateRevBChanging(value);
                    this.SendPropertyChanging();
                    this._DATE_B = value;
                    this.SendPropertyChanged("DateRevB");
                    this.OnDateRevBChanged();
                }
            }
        }

        [Category("Rev C")]
        [global::System.Data.Linq.Mapping.ColumnAttribute(Name = "DATE_C", Storage = "_DATE_C", DbType = "DateTime")]
        public System.Nullable<System.DateTime> DateRevC
        {
            get
            {
                return this._DATE_C;
            }
            set
            {
                if ((this._DATE_C != value))
                {
                    this.OnDateRevCChanging(value);
                    this.SendPropertyChanging();
                    this._DATE_C = value;
                    this.SendPropertyChanged("DateRevC");
                    this.OnDateRevCChanged();
                }
            }
        }

        [Category("Rev D")]
        [global::System.Data.Linq.Mapping.ColumnAttribute(Name = "DATE_D", Storage = "_DATE_D", DbType = "DateTime")]
        public System.Nullable<System.DateTime> DateRevD
        {
            get
            {
                return this._DATE_D;
            }
            set
            {
                if ((this._DATE_D != value))
                {
                    this.OnDateRevDChanging(value);
                    this.SendPropertyChanging();
                    this._DATE_D = value;
                    this.SendPropertyChanged("DateRevD");
                    this.OnDateRevDChanged();
                }
            }
        }

        [Category("Rev E")]
        [global::System.Data.Linq.Mapping.ColumnAttribute(Name = "DATE_E", Storage = "_DATE_E", DbType = "DateTime")]
        public System.Nullable<System.DateTime> DateRevE
        {
            get
            {
                return this._DATE_E;
            }
            set
            {
                if ((this._DATE_E != value))
                {
                    this.OnDateRevEChanging(value);
                    this.SendPropertyChanging();
                    this._DATE_E = value;
                    this.SendPropertyChanged("DateRevE");
                    this.OnDateRevEChanged();
                }
            }
        }

        [Category("Rev F")]
        [global::System.Data.Linq.Mapping.ColumnAttribute(Name = "DATE_F", Storage = "_DATE_F", DbType = "DateTime")]
        public System.Nullable<System.DateTime> DateRevF
        {
            get
            {
                return this._DATE_F;
            }
            set
            {
                if ((this._DATE_F != value))
                {
                    this.OnDateRevFChanging(value);
                    this.SendPropertyChanging();
                    this._DATE_F = value;
                    this.SendPropertyChanged("DateRevF");
                    this.OnDateRevFChanged();
                }
            }
        }

        [Category("Rev G")]
        [global::System.Data.Linq.Mapping.ColumnAttribute(Name = "DATE_G", Storage = "_DATE_G", DbType = "DateTime")]
        public System.Nullable<System.DateTime> DateRevG
        {
            get
            {
                return this._DATE_G;
            }
            set
            {
                if ((this._DATE_G != value))
                {
                    this.OnDateRevGChanging(value);
                    this.SendPropertyChanging();
                    this._DATE_G = value;
                    this.SendPropertyChanged("DateRevG");
                    this.OnDateRevGChanged();
                }
            }
        }

        [Category("Rev A")]
        [global::System.Data.Linq.Mapping.ColumnAttribute(Name = "DESCRIPTION_A", Storage = "_DESCRIPTION_A", DbType = "NVarChar(256)")]
        public string DescriptionRevA
        {
            get
            {
                return this._DESCRIPTION_A;
            }
            set
            {
                if ((this._DESCRIPTION_A != value))
                {
                    this.OnDescriptionRevAChanging(value);
                    this.SendPropertyChanging();
                    this._DESCRIPTION_A = value;
                    this.SendPropertyChanged("DescriptionRevA");
                    this.OnDescriptionRevAChanged();
                }
            }
        }

        [Category("Rev B")]
        [global::System.Data.Linq.Mapping.ColumnAttribute(Name = "DESCRIPTION_B", Storage = "_DESCRIPTION_B", DbType = "NVarChar(256)")]
        public string DescriptionRevB
        {
            get
            {
                return this._DESCRIPTION_B;
            }
            set
            {
                if ((this._DESCRIPTION_B != value))
                {
                    this.OnDescriptionRevBChanging(value);
                    this.SendPropertyChanging();
                    this._DESCRIPTION_B = value;
                    this.SendPropertyChanged("DescriptionRevB");
                    this.OnDescriptionRevBChanged();
                }
            }
        }

        [Category("Rev C")]
        [global::System.Data.Linq.Mapping.ColumnAttribute(Name = "DESCRIPTION_C", Storage = "_DESCRIPTION_C", DbType = "NVarChar(256)")]
        public string DescriptionRevC
        {
            get
            {
                return this._DESCRIPTION_C;
            }
            set
            {
                if ((this._DESCRIPTION_C != value))
                {
                    this.OnDescriptionRevCChanging(value);
                    this.SendPropertyChanging();
                    this._DESCRIPTION_C = value;
                    this.SendPropertyChanged("DescriptionRevC");
                    this.OnDescriptionRevCChanged();
                }
            }
        }

        [Category("Rev D")]
        [global::System.Data.Linq.Mapping.ColumnAttribute(Name = "DESCRIPTION_D", Storage = "_DESCRIPTION_D", DbType = "NVarChar(256)")]
        public string DescriptionRevD
        {
            get
            {
                return this._DESCRIPTION_D;
            }
            set
            {
                if ((this._DESCRIPTION_D != value))
                {
                    this.OnDescriptionRevDChanging(value);
                    this.SendPropertyChanging();
                    this._DESCRIPTION_D = value;
                    this.SendPropertyChanged("DescriptionRevD");
                    this.OnDescriptionRevDChanged();
                }
            }
        }

        [Category("Rev E")]
        [global::System.Data.Linq.Mapping.ColumnAttribute(Name = "DESCRIPTION_E", Storage = "_DESCRIPTION_E", DbType = "NVarChar(256)")]
        public string DescriptionRevE
        {
            get
            {
                return this._DESCRIPTION_E;
            }
            set
            {
                if ((this._DESCRIPTION_E != value))
                {
                    this.OnDescriptionRevEChanging(value);
                    this.SendPropertyChanging();
                    this._DESCRIPTION_E = value;
                    this.SendPropertyChanged("DescriptionRevE");
                    this.OnDescriptionRevEChanged();
                }
            }
        }

        [Category("Rev F")]
        [global::System.Data.Linq.Mapping.ColumnAttribute(Name = "DESCRIPTION_F", Storage = "_DESCRIPTION_F", DbType = "NVarChar(256)")]
        public string DescriptionRevF
        {
            get
            {
                return this._DESCRIPTION_F;
            }
            set
            {
                if ((this._DESCRIPTION_F != value))
                {
                    this.OnDescriptionRevFChanging(value);
                    this.SendPropertyChanging();
                    this._DESCRIPTION_F = value;
                    this.SendPropertyChanged("DescriptionRevF");
                    this.OnDescriptionRevFChanged();
                }
            }
        }

        [Category("Rev G")]
        [global::System.Data.Linq.Mapping.ColumnAttribute(Name = "DESCRIPTION_G", Storage = "_DESCRIPTION_G", DbType = "NVarChar(256)")]
        public string DescriptionRevG
        {
            get
            {
                return this._DESCRIPTION_G;
            }
            set
            {
                if ((this._DESCRIPTION_G != value))
                {
                    this.OnDescriptionRevGChanging(value);
                    this.SendPropertyChanging();
                    this._DESCRIPTION_G = value;
                    this.SendPropertyChanged("DescriptionRevG");
                    this.OnDescriptionRevGChanged();
                }
            }
        }

        [Category("Rev A")]
        [global::System.Data.Linq.Mapping.ColumnAttribute(Name = "APPRV_BY_A", Storage = "_APPRV_BY_A", DbType = "NVarChar(20)")]
        public string ApprovedByRevA
        {
            get
            {
                return this._APPRV_BY_A;
            }
            set
            {
                if ((this._APPRV_BY_A != value))
                {
                    this.OnApprovedByRevAChanging(value);
                    this.SendPropertyChanging();
                    this._APPRV_BY_A = value;
                    this.SendPropertyChanged("ApprovedByRevA");
                    this.OnApprovedByRevAChanged();
                }
            }
        }

        [Category("Rev B")]
        [global::System.Data.Linq.Mapping.ColumnAttribute(Name = "APPRV_BY_B", Storage = "_APPRV_BY_B", DbType = "NVarChar(20)")]
        public string ApprovedByRevB
        {
            get
            {
                return this._APPRV_BY_B;
            }
            set
            {
                if ((this._APPRV_BY_B != value))
                {
                    this.OnApprovedByRevBChanging(value);
                    this.SendPropertyChanging();
                    this._APPRV_BY_B = value;
                    this.SendPropertyChanged("ApprovedByRevB");
                    this.OnApprovedByRevBChanged();
                }
            }
        }

        [Category("Rev C")]
        [global::System.Data.Linq.Mapping.ColumnAttribute(Name = "APPRV_BY_C", Storage = "_APPRV_BY_C", DbType = "NVarChar(20)")]
        public string ApprovedByRevC
        {
            get
            {
                return this._APPRV_BY_C;
            }
            set
            {
                if ((this._APPRV_BY_C != value))
                {
                    this.OnApprovedByRevCChanging(value);
                    this.SendPropertyChanging();
                    this._APPRV_BY_C = value;
                    this.SendPropertyChanged("ApprovedByRevC");
                    this.OnApprovedByRevCChanged();
                }
            }
        }

        [Category("Rev D")]
        [global::System.Data.Linq.Mapping.ColumnAttribute(Name = "APPRV_BY_D", Storage = "_APPRV_BY_D", DbType = "NVarChar(20)")]
        public string ApprovedByRevD
        {
            get
            {
                return this._APPRV_BY_D;
            }
            set
            {
                if ((this._APPRV_BY_D != value))
                {
                    this.OnApprovedByRevDChanging(value);
                    this.SendPropertyChanging();
                    this._APPRV_BY_D = value;
                    this.SendPropertyChanged("ApprovedByRevD");
                    this.OnApprovedByRevDChanged();
                }
            }
        }

        [Category("Rev E")]
        [global::System.Data.Linq.Mapping.ColumnAttribute(Name = "APPRV_BY_E", Storage = "_APPRV_BY_E", DbType = "NVarChar(20)")]
        public string ApprovedByRevE
        {
            get
            {
                return this._APPRV_BY_E;
            }
            set
            {
                if ((this._APPRV_BY_E != value))
                {
                    this.OnApprovedByRevEChanging(value);
                    this.SendPropertyChanging();
                    this._APPRV_BY_E = value;
                    this.SendPropertyChanged("ApprovedByRevE");
                    this.OnApprovedByRevEChanged();
                }
            }
        }

        [Category("Rev F")]
        [global::System.Data.Linq.Mapping.ColumnAttribute(Name = "APPRV_BY_F", Storage = "_APPRV_BY_F", DbType = "NVarChar(20)")]
        public string ApprovedByRevF
        {
            get
            {
                return this._APPRV_BY_F;
            }
            set
            {
                if ((this._APPRV_BY_F != value))
                {
                    this.OnApprovedByRevFChanging(value);
                    this.SendPropertyChanging();
                    this._APPRV_BY_F = value;
                    this.SendPropertyChanged("ApprovedByRevF");
                    this.OnApprovedByRevFChanged();
                }
            }
        }

        [Category("Rev G")]
        [global::System.Data.Linq.Mapping.ColumnAttribute(Name = "APPRV_BY_G", Storage = "_APPRV_BY_G", DbType = "NVarChar(20)")]
        public string ApprovedByRevG
        {
            get
            {
                return this._APPRV_BY_G;
            }
            set
            {
                if ((this._APPRV_BY_G != value))
                {
                    this.OnApprovedByRevGChanging(value);
                    this.SendPropertyChanging();
                    this._APPRV_BY_G = value;
                    this.SendPropertyChanged("ApprovedByRevG");
                    this.OnApprovedByRevGChanged();
                }
            }
        }

        [global::System.Data.Linq.Mapping.ColumnAttribute(Name = "COMMENTS", Storage = "_Comments", DbType = "NVarChar(256)")]
        public string Comments
        {
            get
            {
                return this._Comments;
            }
            set
            {
                if ((this._Comments != value))
                {
                    this.OnCommentsChanging(value);
                    this.SendPropertyChanging();
                    this._Comments = value;
                    this.SendPropertyChanged("Comments");
                    this.OnCommentsChanged();
                }
            }
        }

        public event PropertyChangingEventHandler PropertyChanging;

        public event PropertyChangedEventHandler PropertyChanged;

        protected virtual void SendPropertyChanging()
        {
            if ((this.PropertyChanging != null))
            {
                this.PropertyChanging(this, emptyChangingEventArgs);
            }
        }

        protected virtual void SendPropertyChanged(String propertyName)
        {
            if ((this.PropertyChanged != null))
            {
                this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
            }
        }

        public object Clone()
        {
            return this.MemberwiseClone();
        }
    }
}
#pragma warning restore 1591
